collabora/WhisperLive

server.py

Fix warning 
```
UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at C:\cb\pytorch_1000000000000\work\torch\csrc\utils\tensor_numpy.cpp:205.)
speech_prob = self.vad_model(torch.from_numpy(frame_np), self.RATE).item()
```
https://github.com/collabora/whisper-live/issues/9

copy np array to make tensor writable

---

Audio-Transcription-Chrome/background.js
Audio-Transcription-Chrome/content.js
Audio-Transcription-Chrome/options.html
Audio-Transcription-Chrome/options.js
Audio-Transcription-Chrome/popup.js
Audio-Transcription-Firefox/background.js
Audio-Transcription-Firefox/content.js
Audio-Transcription-Firefox/popup.html
Audio-Transcription-Firefox/popup.js
run_server.py
setup.py
whisper_live/client.py
whisper_live/server.py

- resolve mozilla client; not (empty)sending audio frames when content is paused.
- add client queue to support 4 clients at a time 10 minutes each.
- send wait time to clients waiting in the queue
- show popup in chrome/mozilla client with estimated wait time
- update python client to handle server messages

Add client queue

---

setup.sh

`subprocess.run(["wget", "-O", model_filename, model_url], check=True)` breaks the server because wget is not installed

add wget to setup.sh

---

README.md
whisper_live/client.py

This resolves https://github.com/collabora/WhisperLive/issues/62 feature requets.
It can be tested with:
```
client = TranscriptionClient(host, port, is_multilingual=True, lang="en", translate=False) 
client(hls_url="http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_1xtra/bbc_1xtra.isml/bbc_1xtra-audio%3d96000.norewind.m3u8") 
```
This could be added to the README.me

Support for HLS transcription (resolves #62)

---

whisper_live/server.py

Fixes #87 
Code review needed.

refactor: add `format_segment` helper to standardize timestamp output

---

whisper_live/server.py

fix: `initial_prompt` and `vad_params` key error if client doesnt send those params

fix: key error

---

README.md

Wrong param name in examples in README

Fix transcribe examples

---

Audio-Transcription-Chrome/options.js
Audio-Transcription-Firefox/content.js

In latest version, brower extension is not working anymore. 
Here is the server side errors:
```
Traceback (most recent call last):
File "/home/gchust/miniconda3/envs/whisperlive/lib/python3.11/site-packages/websockets/sync/server.py", line 499, in conn_handler
handler(connection)
File "/mnt/c/work/WhisperLive/whisper_live/server.py", line 168, in recv_audio
model=options["model"],
~~~~~~~^^^^^^^^^
KeyError: 'model'
```
This is the payload send from the web browser extension
```
{'uid': '620a44b8-38d3-4967-8f36-df7272aa8eb4', 'multilingual': False, 'language': 'zh', 'task': 'transcribe', 'model_size': 'small'}
```
Looks like server expecting `model` from client. 
After the fix, I am able to use the extension now:

fix: keyError: 'model' in server, when using browser extension

---

TensorRT_whisper.md
requirements/server.txt
whisper_live/server.py
whisper_live/transcriber_tensorrt.py

- update requirements
- tensorrt engine warmup

Tensorrt model warmup

---

whisper_live/client.py
whisper_live/server.py

- add no speech threshold to filter segments
- save srt file at the end of the session

Save transcript

---

requirements/server.txt

The server script uses scipy but is not installed with the current server requirements file.

Add scipy to server.txt

---

.github/workflows/ci.yml
README.md
docker/Dockerfile.cpu
docker/Dockerfile.gpu

- push docker containers to ghcr on every new released version

Docker ghcr ci

---

whisper_live/server.py
whisper_live/transcriber.py

Should fix: https://github.com/collabora/WhisperLive/issues/137
Basically, the problem was that we were processing the audio through whisper model even when there was no voice activity and too quickly.

fix: cpu usage issue

---

whisper_live/client.py

On systems without a mic, catch the OSError and print a WARN log instead of just crashing.
In my case, I was just trying to do `client(hls_url=my_url)` which does not need a mic.
Example error on systems without mics.
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-1bb0e2c6471f> in <cell line: 26>()
48     sleep(15)
49     logging.info("Starting client")
---> 50     client = TranscriptionClient(
51         host="localhost",
52         port=port,
3 frames
/usr/local/lib/python3.10/dist-packages/whisper_live/client.py in __init__(self, host, port, lang, translate, model, use_vad)
508     """
509     def __init__(self, host, port, lang=None, translate=False, …
```

Handle failure on systems without microphones

---

docker/Dockerfile.cpu
docker/Dockerfile.gpu

I added a few improvements to the docker files, which result in much smaller images.
Here a comparison:
```
REPOSITORY   TAG         IMAGE ID       CREATED          SIZE  
wl-new       0.4.1-cpu   206a09e7f64e   3 hours ago      3.34GB
wl-old       0.4.1-cpu   9634667f608b   4 hours ago      9.92GB
```
```
REPOSITORY   TAG         IMAGE ID       CREATED          SIZE  
wl-new       0.4.1-gpu   46bef0dedc60   13 seconds ago   7.2GB 
wl-old       0.4.1-gpu   9d620744a852   3 hours ago      13.4GB
```
The main tricks:
- On the cpu file, install torch-cpu, so that all those unnecessary nvidia-wheels with the shared libs are not installed.
- On the gpu file, don't use nvidia base images, because torch will install the libs in the nvidia-wheels anyway and we don't need them twice.
- In general, …

Improve cpu and gpu Dockerfiles, resulting in much smaller images

---

README.md
whisper_live/client.py
whisper_live/transcriber.py

Fixes https://github.com/collabora/WhisperLive/issues/141

Make writing audio frames optional

---

whisper_live/client.py

This pull request addresses issue #183. The feature request is to customize the location of the client transcription.
Added an argument to TranscriptionClient to specify the location where the transcription file should be saved.
```python
from whisper_live.client import TranscriptionClient
client = TranscriptionClient(
"localhost",
9090,
lang="en",
translate=False,
model="small",
use_vad=False,
output_transcription_path="my_customized_output.srts"    # Specify the location of transcription
)
client(
hls_url="http://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_1xtra/bbc_1xtra.isml/bbc_1xtra-audio%3d96000.norewind.m3u8")
```
Fixes #183

Expose the srt file location of Transcription client

---

README.md
run_server.py
whisper_live/server.py

I added a mode in which all client connections use the same single model, instead of instantiating a new model for each connection. This only applies if a custom model has been specified at server start (i.e. a trt model or a custom fw model).
For this a new option has been added, defaulting to false, so that the current behaviour is not changed.
This partially resolves #109, but only for custom models. It does not apply for a fw-backend which dynamically loads standard-models based on the client request.
A thread lock is used, to make model prediction thread safe. But this also means that connections have to wait, if another connection currently predicts.
I use a large-v3 tensorrt model. It would take 5secs to load for every new client connection. With the single model option, this is …

Single model mode

---

README.md

Without backslash, shell interprets `-fw` as new command

Backslash missing in example

---

whisper_live/server.py

I kept accidentally typing "faster-whisper" instead of "faster_whisper" today. This caused the server to error out with something along the lines of "the variable named 'client' referenced before assignment" every time I tried to establish a web socket connection. It took me an hour to realise what the issue was. 
This PR prevents such a thing from happening again by erroring out early with a good descriptive message. It also allows adding more backends types in a safer way.

Making backend arg safer

---

requirements/server.txt
whisper_live/vad.py

https://github.com/snakers4/silero-vad relased a new version, which breaks for WhisperLive. So, for a quick fix, pinning version to v4.0

Pin silero VAD onnx model version to v4.0

---

README.md
docker/Dockerfile.tensorrt
requirements/server.txt

- Upgrades TensorRT-LLM==`0.10.0`.
- Fixes requirements to have torch compatible with tensorrt-llm.
- Should Fix https://github.com/collabora/WhisperLive/issues/261.

Upgrade tensorrt-llm==`0.10.0`

---

README.md
requirements/server.txt
tests/test_client.py
tests/test_server.py
whisper_live/client.py
whisper_live/server.py

Adds feature request from #256

Expose client manager args

---

tests/test_client.py
whisper_live/client.py
whisper_live/server.py

This PR stabalises the srt file writing and makes sure that the completed segments are stored in memory to be written into a srt file at the end of the sesion.

Fix srt file missing segments

---

requirements/server.txt
whisper_live/client.py
whisper_live/server.py
whisper_live/transcriber.py

- Upgrade to faster_whisper==1.1.0rc0
- Enables whisper-turbo
- Minor fixes that improves punctatuations

Upgrade faster-whisper 1.1.0rc0

---

requirements/server.txt

Latest version of tokenizers==0.21.0 doesnt support python 3.8 so, pinning `tokenizers==0.20.3`

Fix requirements & tests for py38

---

.github/workflows/ci.yml

Tensorrt docker image building fails in ci because of timeout being set to 20 minutes. This PR sets the timeout to 60 minutes.

Set docker tesnorrt job timeout to 60 mins

---

setup.py
whisper_live/server.py

Fixes potential data inconsistency by adding locks to update and read thread shared variables.
Should close #304

Add lock to thread shared variables updates/reads

---

whisper_live/server.py

While incrementing the timestamp offset for the audio frames if a segment is repeated `n` number of times we should ideally increment it by the end time of the first repitition of this segment otherwise it is possible that we include some of the audio from the next segment which is not yet transcribed and is lost forever.
This PR records the end time of the first repitition and uses that to increment the timestamp offset if the number of repititions are more than the threshold.

Fix skipped audio chunk

---

docker/Dockerfile.tensorrt

Reduce the size of docker image to be able to build & push the image to github container registery.

Revert to 12.4.1 base image

---

whisper_live/client.py

This PR adds support for secure WebSocket connections (WSS) to the whisper_live client. Based on #372 
Added a new use_wss parameter (default: False) to the Client class constructor
Modified the WebSocket URL construction to use either ws:// or wss:// protocol prefix based on the use_wss setting
Propagated the use_wss parameter through the TranscriptionClient class constructor
This implementation uses a boolean flag (use_wss) rather than inferring the protocol from the port number as proposed in PR #308. This approach has several advantages:
- WSS can run on any port, not just 443. Many deployments use non-standard ports like 8443 or 9443 for secure WebSockets.
- Users can explicitly choose their preferred protocol regardless of port number.
- Works with various proxy and load balancer …

Add: support for secure WebSocket (WSS) connections

---

README.md
requirements/server.txt
run_server.py
whisper_live/backend/faster_whisper_backend.py
whisper_live/server.py

Enables automatic conversion of custom huggingface whisper models.

Auto convert hf custom whisper to ct2(faster-whisper)
