Audio-Transcription/background.js, Audio-Transcription/content.js, Audio-Transcription/manifest.json, Audio-Transcription/workers/Mp3Worker.js, Audio-Transcription/workers/WavWorker.js
Add transcription element to the Chrome plugin.
=> Add transcription element.

Audio-Transcription-Firefox/content.js, Audio-Transcription/options.js, client.py, requirements/server.txt, server.py
- update faster whisper
- wait for server to be ready before sending audio chunks
=> Update faster whisper

Dockerfile, README.md, requirements/server.txt, server.py
- add dockerfile
- update readme to build docker container
=> add Dockerfile

Dockerfile
- update base image to ```nvidia/cuda:11.2.2-cudnn8-runtime-ubuntu20.04```
=> update cuda devel to  runtime image

server.py
Should close https://github.com/collabora/WhisperLive/issues/23
=> fix: frames_offset typo

run_server.py
Use the updated run method to start the server.
=> Use the updated run method to start the server.

README.md
=> Add contact details.

README.md
Was getting an error trying this out and noticed the docs are bit off from the code.
=> Minor tweaks to documentation

whisper_live/client.py
https://github.com/collabora/WhisperLive/issues/41
=> close websocket after consuming file

whisper_live/client.py
Was looking to use this, realized there was a lot of cleanup that could be done to the python client script.
=> Tidy up the client python file

whisper_live/vad.py
- add arg and default to `True`
=> Add `force_onnx_cpu` arg

README.md
Corrected spelling of Transcribe, and selected language
=> README Spelling correction 

Audio-Transcription-Chrome/popup.html, Audio-Transcription-Firefox/popup.html, requirements/server.txt, setup.py, whisper_live/server.py, whisper_live/transcriber.py
=> feat: Add the `large-v3` model

whisper_live/client.py
fix exception on overflow when call client.
=> fix exception on overflow

whisper_live/server.py
=> feat: set initial_prompt and vad_parameters in the first message

whisper_live/server.py, whisper_live/transcriber.py
Adds a description to exception for them to be more readable.
=> fix: error messages

Audio-Transcription-Chrome/popup.js, Audio-Transcription-Firefox/popup.js, run_server.py, whisper_live/client.py, whisper_live/server.py
- add option to use custom fine tuned model
=> Change model size param name

whisper_live/client.py, whisper_live/server.py
Remove `use_custom_model` from client i.e. server controls custom model usage
=> Server to control custom model usage

whisper_live/client.py
- remove `multilingual` debug stat
=> fix: typo; remove multilingual debug stat

.github/workflows/ci.yml, docker/Dockerfile.gpu
Fixes https://github.com/collabora/WhisperLive/issues/153
=> Fix docker image gpu

whisper_live/server.py
Fixes https://github.com/collabora/WhisperLive/issues/155
=> fix: lanuguage, task prefix in decoder start ids

docker/Dockerfile.gpu, requirements/server.txt, whisper_live/transcriber.py
Upgrades faster_whisper version to 1.0.1 which has some bug fixes and cuda version upgrade to CUDA12.
Should close https://github.com/collabora/WhisperLive/issues/159
=> Upgrade faster whisper==1.0.1

setup.py
The faster whisper version in setup.py is out of date.
Just updating it to 1.0.1.
=> Fix faster whisper version in setup.py

tests/test_client.py, tests/test_server.py, whisper_live/client.py
=> Add support for processing same audio stream via multiple clients running different tasks.

whisper_live/client.py
=> Fix client close

README.md, whisper_live/client.py
Hi, Thank you for doing the repository. It's handy.
I've added RTSP stream support to consume audio from microphones
=> Add support for RTSP stream

.github/workflows/ci.yml, README.md, TensorRT_whisper.md, docker/Dockerfile.tensorrt, scripts/build_whisper_tensorrt.sh, whisper_live/transcriber_tensorrt.py
- Use `pip install tensorrt_llm` instead of building `tensorrt_llm` from scratch in Dockerfile
=> Update tensorrt llm to v0.9.0

requirements/server.txt, whisper_live/client.py, whisper_live/server.py
Fixes https://github.com/collabora/WhisperLive/issues/246
=> Discard no speech segments

whisper_live/server.py
=> Initialize last_segment to None

README.md, whisper_live/server.py
Allows users to load models from huggingface
=> Support loading hf models

README.md, TensorRT_whisper.md, docker/Dockerfile.tensorrt, scripts/build_whisper_tensorrt.sh, whisper_live/client.py, whisper_live/transcriber_tensorrt.py
- Upgrade TensorRTLLM to `v0.15.0`.
- Add option to build `INT4/INT8` weight only tensorrt whisper models.
=> Upgrade tensorrt_llm==0.15.0

.github/workflows/ci.yml, README.md, docker/Dockerfile.tensorrt, requirements/client.txt, requirements/server.txt, scripts/setup.sh, setup.py, whisper_live/client.py, whisper_live/tensorrt_utils.py, whisper_live/utils.py
Thanks to @BBC-Esq for opening the PR initially => #194 which motivated this change.
=> Replace ffmpeg with av lib for resampling, rtsp & hls streams

.github/workflows/ci.yml, requirements/server.txt
- Upgrade onnxruntime to support python3.12
- Add python3.12 to ci python matrix
Should close #300
=> Add support py 312

whisper_live/backend/base.py, whisper_live/backend/faster_whisper_backend.py, whisper_live/backend/openvino_backend.py, whisper_live/backend/trt_backend.py
Should close https://github.com/collabora/WhisperLive/issues/356
=> Remove blank segment feature

README.md, TensorRT_whisper.md, docker/Dockerfile.tensorrt, run_server.py, scripts/build_whisper_tensorrt.sh, whisper_live/backend/trt_backend.py, whisper_live/server.py, whisper_live/transcriber/transcriber_tensorrt.py
- Upgrade tensorrt_llm to `v0.18.2`
- Add options to start the tensorrt server with cpp or python session.
=> Upgrade tensorrt_llm to v0.18.2

tests/test_client.py, whisper_live/backend/base.py, whisper_live/backend/faster_whisper_backend.py, whisper_live/backend/openvino_backend.py, whisper_live/backend/trt_backend.py, whisper_live/client.py, whisper_live/server.py
=> Add possibility to configure more parameters

whisper_live/client.py
Request to output transcriptions via a callback function instead of console output 
Closes #361
=> Add transcription callback to Client for handling transcription results

whisper_live/client.py
Request to output transcriptions via a callback function instead of console output
#361
=> Add transcription callback parameter to TranscriptionClient #361

scripts/setup.sh
Adding a small improvement to the setup.sh script to run it on MacOS
=> make setup.sh to work on macos

Audio-Transcription-Chrome/README.md, Audio-Transcription-Chrome/audiopreprocessor.js, Audio-Transcription-Chrome/background.js, Audio-Transcription-Chrome/content.js, Audio-Transcription-Chrome/manifest.json, Audio-Transcription-Chrome/options.js, Audio-Transcription-Chrome/popup.html, Audio-Transcription-Chrome/popup.js, Audio-Transcription-Firefox/README.md, Audio-Transcription-Firefox/audiopreprocessor.js, Audio-Transcription-Firefox/content.js, Audio-Transcription-Firefox/manifest.json, Audio-Transcription-Firefox/popup.html, Audio-Transcription-Firefox/popup.js
- Update deprecated media processor to AudioWorklet
- Add option to download srt file at the end of the session i.e. at stop capture
=> Add srt download opt browser ext
